// 100 位动态商铺访客 - 根据商铺等级逐步解锁
// type: tourist | citizen | tycoon | expert | special
// headIcon: 人头图标 | phrases: 10句个性化话术（应对不同情况）

export const SHOP_NPC_POOL = [
  // 类别一：小白与游客 (1-20) headIcon 人头
  { id: 'tourist_1', name: '迷路的跟团大妈', type: 'tourist', knowledge: 0.05, budget: [5, 15], minShopLv: 1, headIcon: '👩', phrases: ['随便看看~', '跟团走散了', '翡翠能保值吗', '给闺女买一个', '这块够大吗', '便宜点行不', '不懂啊看看', '导游说这靠谱', '买块纪念', '等团友来'] },
  { id: 'tourist_2', name: '第一次给女友买礼物的直男', type: 'tourist', knowledge: 0.02, budget: [3, 8], minShopLv: 1, headIcon: '👦', phrases: ['送女朋友买啥好', '她喜欢绿色', '贵点也行', '有寓意好的吗', '平安扣咋样', '包装好看吗', '别踩雷', '预算三千够吗', '她会不会喜欢', '老板推荐下'] },
  { id: 'tourist_3', name: '穷游背包客', type: 'tourist', knowledge: 0.08, budget: [0.5, 2], minShopLv: 1, headIcon: '🧑', phrases: ['就看看', '最便宜多少', '能砍价吗', '背包客预算有限', '小件有吗', '纪念品级别就行', '不买也能看看吧', '下次有钱再来', '逛逛', '行吧走了'] },
  { id: 'tourist_4', name: '凑热闹的吃瓜大学生', type: 'tourist', knowledge: 0.1, budget: [0.2, 1], minShopLv: 1, headIcon: '🧑', phrases: ['开开眼界', '翡翠这么贵啊', '冰种是啥', '拍个照', '买不起看看', '长知识了', '直播里见过', '纯围观', '有意思', '撤了撤了'] },
  { id: 'tourist_5', name: '迷信转运的中年阿姨', type: 'tourist', knowledge: 0.06, budget: [2, 6], minShopLv: 1, headIcon: '👩', phrases: ['要带绿的', '能辟邪吗', '大师说我要戴玉', '转运的哪种好', '平安扣保平安', '有开过光的吗', '这块有灵性', '买来冲冲喜', '讲究个寓意', '就它了'] },
  { id: 'tourist_6', name: '刚发工资的小白领', type: 'tourist', knowledge: 0.12, budget: [5, 12], minShopLv: 1, headIcon: '🧑', phrases: ['奖励自己一下', '发薪日买买买', '小件有吗', '别超预算', '好看就行', '同事都戴', '冲动消费一把', '这个挺精致', '算了存钱', '下次再说'] },
  { id: 'tourist_7', name: '外地旅游团导游', type: 'tourist', knowledge: 0.15, budget: [8, 25], minShopLv: 1, headIcon: '👨', phrases: ['带团路过', '有回扣吗开玩笑', '团友想买', '拿几件看看', '量大能便宜吗', '品质要过得去', '别坑我的人', '靠谱的来', '合作愉快', '下次还来'] },
  { id: 'tourist_8', name: '想捡漏的街溜子', type: 'tourist', knowledge: 0.2, budget: [0.5, 3], minShopLv: 1, headIcon: '😏', phrases: ['有啥漏可捡', '五十块卖不', '当我是冤种', '便宜甩的有没有', '别蒙我', '看看再说', '出个价', '太贵了', '走人', '呸'] },
  { id: 'tourist_9', name: '买纪念品的外国游客', type: 'tourist', knowledge: 0.03, budget: [10, 30], minShopLv: 1, headIcon: '👱', phrases: ['Jade?', 'For souvenir', 'How much?', 'Beautiful', 'Traditional?', 'For my wife', 'Expensive', 'Nice shop', 'Maybe later', 'Thank you'] },
  { id: 'tourist_10', name: '给孙子买满月礼的老奶奶', type: 'tourist', knowledge: 0.04, budget: [2, 8], minShopLv: 1, headIcon: '👵', phrases: ['孙儿满月', '平安扣好', '保平安的', '小点轻点', '别太贵', '老人家不懂', '心意到了就行', '这块成吗', '就它吧', '谢谢老板'] },
  { id: 'tourist_11', name: '盲目跟风的短视频受众', type: 'tourist', knowledge: 0.05, budget: [3, 10], minShopLv: 1, headIcon: '🧑', phrases: ['网红同款有吗', '刷到过这家', '冰种火啊', '跟风买一个', '拍照好看', '不懂但想买', '便宜点的', '算了不买了', '下次吧', '溜了'] },
  { id: 'tourist_12', name: '拿着网图找同款的少女', type: 'tourist', knowledge: 0.02, budget: [0.3, 0.5], minShopLv: 1, headIcon: '👧', phrases: ['有这款吗', '网图同款', '三千能买到吗', '玻璃种诶', '太贵了', '仿的也行', '梦想破灭', '看看而已', '走啦', '拜拜'] },
  { id: 'tourist_13', name: '醉醺醺的酒鬼', type: 'tourist', knowledge: 0.01, budget: [5, 50], minShopLv: 1, headIcon: '🧑', phrases: ['再...再来一杯', '这啥店', '玉？绿的？', '买了', '多少钱', '刷卡', '好晃', '我清醒着呢', '翡翠好吃吗', '走错门了'] },
  { id: 'tourist_14', name: '刚中彩票的暴发户底层', type: 'tourist', knowledge: 0.05, budget: [50, 200], minShopLv: 1, headIcon: '🧑', phrases: ['有钱了！', '最贵的拿来', '不差钱', '这块我要', '再来几件', '中奖了嘿嘿', '显摆显摆', '老板包起来', '爽', '明天再来'] },
  { id: 'tourist_15', name: '离家出走的叛逆少爷', type: 'tourist', knowledge: 0.08, budget: [20, 80], minShopLv: 1, headIcon: '🧑', phrases: ['随便买点', '当铺能当多少', '换现', '贵的就行', '不问价', '打包', '走了', '别跟我爸说', '哼', '下次'] },
  { id: 'tourist_16', name: '被网文洗脑的中二少年', type: 'tourist', knowledge: 0, budget: [1, 5], minShopLv: 1, headIcon: '👦', phrases: ['有灵石吗', '能修仙那种', '蕴含灵气吗', '老板你懂吗', '修真用的', '没有？', '凡俗之物', '告辞', '异世界见', '唉'] },
  { id: 'tourist_17', name: '想要装杯的精神小伙', type: 'tourist', knowledge: 0.06, budget: [2, 8], minShopLv: 1, headIcon: '👨', phrases: ['够派头吗', '戴出去有面', '最闪的', '便宜货别拿', '就这？', '行吧将就', '兄弟们都看我', '可以可以', '撤', '下次整更好的'] },
  { id: 'tourist_18', name: '买来垫桌角的奇葩大叔', type: 'tourist', knowledge: 0.02, budget: [1, 5], minShopLv: 1, headIcon: '👨', phrases: ['有方的不', '垫桌子用', '砖头料就行', '便宜结实', '不讲究', '这块够方', '就它', '实用主义', '走', '谢了'] },
  { id: 'tourist_19', name: '和闺蜜攀比的塑料姐妹花', type: 'tourist', knowledge: 0.07, budget: [8, 25], minShopLv: 1, headIcon: '👩', phrases: ['她买的我也要', '比她的好', '闪吗', '显白吗', '拍照好看', '不能输', '就这个', '比她那个贵吧', '满意', '走炫耀去'] },
  { id: 'tourist_20', name: '走错门的买菜大爷', type: 'tourist', knowledge: 0, budget: [0.1, 0.5], minShopLv: 1, headIcon: '👴', phrases: ['菜市场呢', '这卖啥的', '翡翠？能吃吗', '走错了', '绿的菜呢', '玉石啊', '不懂不懂', '买菜去', '打扰了', '回见'] },

  // 类别二：普通市民 (21-40)
  { id: 'citizen_21', name: '货比三家的精明主妇', type: 'citizen', knowledge: 0.55, budget: [15, 50], minShopLv: 2, headIcon: '👩', phrases: ['别家更便宜', '能打几折', '底价多少', '我再看看', '品质还行', '砍一半行不', '诚意价', '算了', '记下了', '改天'] },
  { id: 'citizen_22', name: '准备金婚纪念的老大爷', type: 'citizen', knowledge: 0.5, budget: [20, 60], minShopLv: 2, headIcon: '👴', phrases: ['金婚礼物', '老伴戴的', '成色要好', '五十周年', '别糊弄', '预算就这些', '平安扣来一对', '可以', '包好点', '谢谢'] },
  { id: 'citizen_23', name: '备婚的小情侣', type: 'citizen', knowledge: 0.45, budget: [30, 80], minShopLv: 2, headIcon: '👩', phrases: ['结婚用的', '成对的有吗', '她喜欢哪个', '预算有限', '要好看的', '能便宜吗', '这对不错', '就它吧', '包起来', '谢谢'] },
  { id: 'citizen_24', name: '广场舞领舞大妈', type: 'citizen', knowledge: 0.4, budget: [10, 35], minShopLv: 2, headIcon: '👩', phrases: ['显眼的有没有', '戴出去跳广场舞', '大的好看', '颜色鲜艳点', '姐妹们都戴', '这块够闪', '便宜点', '行', '下次带姐妹来', '走啦'] },
  { id: 'citizen_25', name: '退休的国企老厂长', type: 'citizen', knowledge: 0.52, budget: [25, 70], minShopLv: 2, headIcon: '👨', phrases: ['沉稳点的', '糯种就行', '不张扬', '挂件有吗', '适合长辈', '品质看得过去', '实价多少', '可以接受', '包上', '谢了'] },
  { id: 'citizen_26', name: '懂一点点皮毛的贴吧老哥', type: 'citizen', knowledge: 0.58, budget: [5, 20], minShopLv: 2, headIcon: '👨', phrases: ['贴吧学的', '种水如何', '有裂吗', 'A货吗', '别蒙我', '半懂不懂', '价格虚高', '底价', '算了', '再研究'] },
  { id: 'citizen_27', name: '刚入坑的新手玩家', type: 'citizen', knowledge: 0.35, budget: [15, 45], minShopLv: 2, headIcon: '🧑', phrases: ['刚玩翡翠', '交学费了', '这块能涨吗', '半明料呢', '不懂就问', '老板指点下', '冲动消费', '买了', '学习', '下次再来'] },
  { id: 'citizen_28', name: '攒了半年零花钱的高中生', type: 'citizen', knowledge: 0.3, budget: [1, 5], minShopLv: 2, headIcon: '👦', phrases: ['就这些钱了', '小戒面有吗', '送妈妈的', '便宜点的', '攒了好久', '够吗', '再便宜点', '好吧', '谢谢', '妈肯定喜欢'] },
  { id: 'citizen_29', name: '给领导买礼物的底层员工', type: 'citizen', knowledge: 0.42, budget: [20, 60], minShopLv: 2, headIcon: '🧑', phrases: ['送礼用的', '包装要好', '有面子', '领导喜欢玉', '别太便宜', '档次够吗', '就这个', '能开发票吗', '谢谢', '拜托了'] },
  { id: 'citizen_30', name: '喜欢盘玉的油腻大叔', type: 'citizen', knowledge: 0.48, budget: [18, 55], minShopLv: 2, headIcon: '👨', phrases: ['盘一盘', '手感如何', '有潜力', '拿手电看看', '油性怎么样', '能盘出来', '价格呢', '考虑下', '下次带家伙来', '走了'] },
  { id: 'citizen_31', name: '做微商的单亲妈妈', type: 'citizen', knowledge: 0.38, budget: [5, 20], minShopLv: 2, headIcon: '👩', phrases: ['拿货价多少', '朋友圈卖', '能代理吗', '便宜批量', '品质别太差', '有图吗', '考虑考虑', '加个微信', '有货联系', '谢了'] },
  { id: 'citizen_32', name: '刚买完房来逛街的房奴', type: 'citizen', knowledge: 0.5, budget: [3, 12], minShopLv: 2, headIcon: '🧑', phrases: ['看看而已', '房贷压死人', '最便宜多少', '过过眼瘾', '算了买不起', '记下了', '等还完贷', '唉', '走了', '祝生意兴隆'] },
  { id: 'citizen_33', name: '爱好收藏的小学语文老师', type: 'citizen', knowledge: 0.55, budget: [12, 40], minShopLv: 2, headIcon: '👩', phrases: ['有特色料吗', '意境好的', '诗情画意', '不俗的', '这块有味道', '文人雅好', '价格合适', '收了', '欣赏', '再会'] },
  { id: 'citizen_34', name: '开五金店的小老板', type: 'citizen', knowledge: 0.45, budget: [15, 50], minShopLv: 2, headIcon: '👨', phrases: ['金镶玉有吗', '喜欢金配玉', '实在', '别花哨', '价格实在', '做生意讲究', '这块可以', '成交', '合作愉快', '走了'] },
  { id: 'citizen_35', name: '刚收完租的包租婆', type: 'citizen', knowledge: 0.6, budget: [50, 150], minShopLv: 2, headIcon: '👩', phrases: ['收租了高兴', '买块犒劳自己', '别骗我', '老娘懂', '实价', '这块成', '包起来', '刷卡', '下次还来', '拜拜'] },
  { id: 'citizen_36', name: '陪老板逛街的秘书', type: 'citizen', knowledge: 0.35, budget: [100, 300], minShopLv: 2, headIcon: '👩', phrases: ['老板让我看看', '预算不限', '要好的', '别问我', '老板您看', '就这个', '刷卡', '谢谢', '走', '下次'] },
  { id: 'citizen_37', name: '想买个传家宝的普通老翁', type: 'citizen', knowledge: 0.5, budget: [30, 90], minShopLv: 2, headIcon: '👴', phrases: ['传给子孙', '要像样的', '别糊弄', '打个电话问问', '家人商量', '这块行', '传家够格', '买了', '谢谢', '走了'] },
  { id: 'citizen_38', name: '刚被股市套牢的股民', type: 'citizen', knowledge: 0.4, budget: [8, 30], minShopLv: 2, headIcon: '👨', phrases: ['买绿的冲冲喜', '股市绿了', '翡翠绿吉利', '转运', '便宜点', '套牢了没钱', '小件就行', '就这个', '涨涨涨', '撤了'] },
  { id: 'citizen_39', name: '挑剔的女装店老板娘', type: 'citizen', knowledge: 0.65, budget: [25, 80], minShopLv: 2, headIcon: '👩', phrases: ['审美不行别拿来', '丑的不要', '搭配衣服用', '精致点', '这块还行', '品质可以', '价格呢', '考虑', '加微信', '走了'] },
  { id: 'citizen_40', name: '赚了第一桶金的外卖小哥', type: 'citizen', knowledge: 0.32, budget: [5, 18], minShopLv: 2, headIcon: '🧑', phrases: ['给妈买', '辛苦钱', '实在的', '别坑', '小镯子', '妈手小', '这块成', '包好', '谢谢', '走了'] },

  // 类别三：商贾与富豪 (41-60)
  { id: 'tycoon_41', name: '煤老板', type: 'tycoon', knowledge: 0.7, budget: [500, 2000], minShopLv: 3, headIcon: '👨', phrases: ['帝王绿有吗', '只要最好的', '钱不是事', '这块我要', '打包', '还有没', '都拿出来', '刷卡', '爽快', '下次'] },
  { id: 'tycoon_42', name: '跨国集团女总裁', type: 'tycoon', knowledge: 0.82, budget: [300, 1000], minShopLv: 3, headIcon: '👩', phrases: ['高冰满绿', '手镯', '其余不看', '品质说话', '就这块', '包起来', '秘书结账', '谢谢', '走', '下次'] },
  { id: 'tycoon_43', name: '娱乐圈当红小花旦', type: 'tycoon', knowledge: 0.6, budget: [200, 800], minShopLv: 3, headIcon: '👩', phrases: ['紫罗兰有吗', '防偷拍', '要特别的', '这款还行', '包严实', '别让人认出', '就它', '助理付款', '谢了', '撤'] },
  { id: 'tycoon_44', name: '神秘的中东土豪', type: 'tycoon', knowledge: 0.5, budget: [1000, 5000], minShopLv: 3, headIcon: '👨', phrases: ['Best one', 'Money no problem', 'Glass type', 'For collection', 'This one', 'Wrap it', 'Card', 'Thank you', 'Good', 'Bye'] },
  { id: 'tycoon_45', name: '福布斯排行榜上的隐形富豪', type: 'tycoon', knowledge: 0.9, budget: [500, 3000], minShopLv: 3, headIcon: '👨', phrases: ['低调的', '内涵', '不张扬', '这块有味道', '可以', '包起来', '转账', '谢', '走', '再会'] },
  { id: 'tycoon_46', name: '风投机构合伙人', type: 'tycoon', knowledge: 0.78, budget: [300, 1500], minShopLv: 3, headIcon: '👨', phrases: ['资产配置', '稀缺性', '流动性', '这块可藏', '估值合理', '收了', '投资', '谢了', '走', '再聊'] },
  { id: 'tycoon_47', name: '高调炫富的富二代小网红', type: 'tycoon', knowledge: 0.45, budget: [150, 600], minShopLv: 3, headIcon: '👦', phrases: ['最贵的', '拍视频用', '要炫', '这块够闪', '买了', '直播开箱', '粉丝等着', '包好', '谢', '拜'] },
  { id: 'tycoon_48', name: '高级会所幕后老板', type: 'tycoon', knowledge: 0.75, budget: [400, 1200], minShopLv: 3, headIcon: '👨', phrases: ['送礼用', '高货', '批量', '要上档次的', '这些都要', '打包', '送人', '谢', '走', '合作'] },
  { id: 'tycoon_49', name: '刚刚套现离场的币圈大佬', type: 'tycoon', knowledge: 0.65, budget: [500, 5000], minShopLv: 3, headIcon: '👨', phrases: ['套现了', '梭哈翡翠', '随便买', '这块', '那块也要', '都包上', 'USDT行吗', '开玩笑', '转账', '走了'] },
  { id: 'tycoon_50', name: '搞房地产的张总老婆', type: 'tycoon', knowledge: 0.7, budget: [200, 800], minShopLv: 3, headIcon: '👩', phrases: ['比王太的绿', '要更绿', '她戴那个', '我要更好的', '这块够绿', '买了', '气死她', '包好', '谢', '走'] },
  { id: 'tycoon_51', name: '带着四个保镖的黑帮老大', type: 'tycoon', knowledge: 0.6, budget: [100, 400], minShopLv: 4, headIcon: '👨', phrases: ['龙牌', '霸气的', '压阵', '这块可以', '够凶', '包上', '现金', '谢了', '走', '再会'] },
  { id: 'tycoon_52', name: '来洗钱的神秘白手套', type: 'tycoon', knowledge: 0.85, budget: [1000, 10000], minShopLv: 4, headIcon: '🧑', phrases: ['高货', '价格你懂', '开高点', '这块', '按说的价', '成交', '转账', '合作愉快', '走', '再联系'] },
  { id: 'tycoon_53', name: '举办世纪婚礼的豪门阔少', type: 'tycoon', knowledge: 0.72, budget: [800, 3000], minShopLv: 4, headIcon: '👨', phrases: ['婚礼用', '冰种以上全要', '打包', '不差钱', '都包上', '送亲友', '刷卡', '谢', '婚期紧', '走了'] },
  { id: 'tycoon_54', name: '纳斯达克敲钟归来的新贵', type: 'tycoon', knowledge: 0.68, budget: [300, 1200], minShopLv: 4, headIcon: '👨', phrases: ['奖励自己', '上市了', '顶级货', '这块可以', '纪念', '买了', '包好', '谢', '走', '再会'] },
  { id: 'tycoon_55', name: '迪拜王室采购代办', type: 'tycoon', knowledge: 0.8, budget: [2000, 10000], minShopLv: 4, headIcon: '👨', phrases: ['Rare only', 'Best quality', 'This one', 'And this', 'Money no issue', 'Wrap all', 'Thank you', 'Good', 'Bye', 'Next'] },
  { id: 'tycoon_56', name: '垄断海鲜市场的海霸王', type: 'tycoon', knowledge: 0.65, budget: [150, 600], minShopLv: 4, headIcon: '👨', phrases: ['水头好的', '像水一样', '这块通透', '可以', '买了', '海鲜换翡翠', '包上', '谢', '走', '再会'] },
  { id: 'tycoon_57', name: '投资艺术品的大银行家', type: 'tycoon', knowledge: 0.92, budget: [500, 5000], minShopLv: 4, headIcon: '👨', phrases: ['传世之作', '可上拍', '这块够格', '收了', '投资', '包好', '转账', '谢', '走', '再会'] },
  { id: 'tycoon_58', name: '财阀家族的老太君', type: 'tycoon', knowledge: 0.95, budget: [1000, 8000], minShopLv: 4, headIcon: '👵', phrases: ['传家玉', '一点瑕疵都不要', '严苛', '这块还行', '再看', '勉强', '包上', '谢', '走', '再会'] },
  { id: 'tycoon_59', name: '刚分完巨额遗产的幸运儿', type: 'tycoon', knowledge: 0.4, budget: [500, 3000], minShopLv: 4, headIcon: '🧑', phrases: ['有钱了', '随便买', '这块那块', '都要', '疯狂消费', '包上', '刷卡', '爽', '走', '明天再来'] },
  { id: 'tycoon_60', name: '全球限量跑车收藏家', type: 'tycoon', knowledge: 0.7, budget: [300, 2000], minShopLv: 4, headIcon: '👨', phrases: ['找新刺激', '车玩腻了', '翡翠试试', '这块可以', '新鲜感', '买了', '包好', '谢', '走', '再会'] },

  // 类别四：行家与同行 (61-80)
  { id: 'expert_61', name: '揭阳玉器市场的老油条', type: 'expert', knowledge: 0.98, budget: [50, 500], minShopLv: 4, headIcon: '👨', phrases: ['底价多少', '1.05倍进货价', '别蒙我', '一眼看穿', '实价', '行就拿', '不行走', '揭阳来的', '懂行', '再会'] },
  { id: 'expert_62', name: '四会天光墟的倒爷', type: 'expert', knowledge: 0.9, budget: [20, 150], minShopLv: 4, headIcon: '👨', phrases: ['糯种豆种', '大批量', '扫货', '便宜甩的', '底价', '能拿多少', '考虑', '加微信', '有货联系', '走了'] },
  { id: 'expert_63', name: '平洲公盘的竞标狂人', type: 'expert', knowledge: 0.95, budget: [100, 800], minShopLv: 4, headIcon: '👨', phrases: ['蒙头料呢', '切好的没意思', '公盘见', '这块还行', '明料将就', '价格', '考虑', '走了', '公盘见', '再会'] },
  { id: 'expert_64', name: '国家级珠宝鉴定师', type: 'expert', knowledge: 1, budget: [80, 400], minShopLv: 4, headIcon: '👨', phrases: ['白手套', '瑕疵在这', '砍价', '别骗', '专业', '底价', '可以考虑', '收了', '谢', '走'] },
  { id: 'expert_65', name: '佳士得拍卖行的寻宝猎人', type: 'expert', knowledge: 0.96, budget: [200, 2000], minShopLv: 4, headIcon: '👨', phrases: ['能上拍吗', '绝版', '秋拍', '这块有潜力', '考虑', '收了', '包好', '谢', '走', '再联系'] },
  { id: 'expert_66', name: '典当行的老朝奉', type: 'expert', knowledge: 0.97, budget: [30, 200], minShopLv: 4, headIcon: '👴', phrases: ['批得一无是处', '然后低价收', '开玩笑', '这块还行', '底价', '考虑', '收了', '谢', '走', '再会'] },
  { id: 'expert_67', name: '瑞丽边境的老原石贩子', type: 'expert', knowledge: 0.93, budget: [50, 300], minShopLv: 4, headIcon: '👨', phrases: ['考察行情', '眼光如何', '这块你多少收的', '还行', '反向推销', '我有料', '考虑', '走了', '再联系', '再会'] },
  { id: 'expert_68', name: '对门竞争对手派来的卧底', type: 'expert', knowledge: 0.92, budget: [10, 50], minShopLv: 4, headIcon: '🕵', phrases: ['挑刺', '这不行那不行', '打压', '底价多少', '贵了', '走', '汇报去', '再会', '哼', '拜拜'] },
  { id: 'expert_69', name: '隐居的高级雕刻大师', type: 'expert', knowledge: 0.94, budget: [100, 600], minShopLv: 4, headIcon: '👨', phrases: ['雕工潜力', '特色料', '怪庄', '这块有戏', '收了', '回去雕', '包好', '谢', '走', '再会'] },
  { id: 'expert_70', name: '缅甸矿区的老坑长', type: 'expert', knowledge: 0.91, budget: [80, 400], minShopLv: 4, headIcon: '👨', phrases: ['视察行情', '料子哪来的', '矿口', '这块还行', '市场价', '了解', '走了', '再会', '谢', '拜'] },
  { id: 'expert_71', name: '专门做高仿B+C货的造假头子', type: 'expert', knowledge: 0.88, budget: [15, 80], minShopLv: 5, headIcon: '👨', phrases: ['砖头料', '便宜的', '造药用', '这块', '底价', '大量要', '加微信', '走了', '再联系', '再会'] },
  { id: 'expert_72', name: '行业协会的主席', type: 'expert', knowledge: 0.96, budget: [300, 1500], minShopLv: 5, headIcon: '👨', phrases: ['镇馆之宝', '展会用', '这块够格', '收了', '包好', '谢', '走', '展会见', '再会', '再见'] },
  { id: 'expert_73', name: '曾经切出过百亿标王的神话人物', type: 'expert', knowledge: 1, budget: [0, 0], minShopLv: 5, headIcon: '👴', phrases: ['看看', '不买', '指点你', '这块注意', '那块还行', '年轻人', '再会', '走了', '祝好运', '拜'] },
  { id: 'expert_74', name: '专做古法金镶玉的老匠人', type: 'expert', knowledge: 0.89, budget: [60, 300], minShopLv: 5, headIcon: '👴', phrases: ['特定裂', '冰种', '镶用', '这块有', '收了', '包好', '谢', '走', '再会', '再见'] },
  { id: 'expert_75', name: '垄断渠道的大盘商', type: 'expert', knowledge: 0.95, budget: [200, 2000], minShopLv: 5, headIcon: '👨', phrases: ['低价全扫', '你价低我全要', '搬空', '考虑', '底价', '成交', '包好', '谢', '走', '合作'] },
  { id: 'expert_76', name: '某玉石鉴定机构所长', type: 'expert', knowledge: 0.99, budget: [100, 800], minShopLv: 5, headIcon: '👨', phrases: ['要证书', '权威', '这块有证吗', '可以考虑', '出证', '收了', '包好', '谢', '走', '再会'] },
  { id: 'expert_77', name: '老一代的相玉师', type: 'expert', knowledge: 0.97, budget: [0, 0], minShopLv: 5, headIcon: '👴', phrases: ['玄学手法', '不买', '剧透', '这块有东西', '那块悬', '年轻人', '走了', '再会', '祝好', '拜'] },
  { id: 'expert_78', name: '专靠捡漏发家致富的传奇捡漏王', type: 'expert', knowledge: 1, budget: [50, 500], minShopLv: 5, headIcon: '👨', phrases: ['标错价了吗', '少个零', '秒杀', '没有啊', '遗憾', '走了', '下次', '再会', '盯紧点', '拜'] },
  { id: 'expert_79', name: '做高端私人订制的设计师', type: 'expert', knowledge: 0.9, budget: [150, 1000], minShopLv: 5, headIcon: '👩', phrases: ['多色', '罕见', '这块有', '设计用', '收了', '包好', '谢', '走', '成品见', '再会'] },
  { id: 'expert_80', name: '破产的同行前老板', type: 'expert', knowledge: 0.85, budget: [5, 30], minShopLv: 5, headIcon: '👨', phrases: ['东山再起', '淘点便宜', '底价', '这块', '将就', '收了', '谢', '走', '再会', '祝我好运'] },

  // 类别五：特殊与奇葩 (81-100)
  { id: 'special_81', name: '寻龙定穴的风水先生', type: 'special', knowledge: 0.3, budget: [20, 100], minShopLv: 2, headIcon: '👴', phrases: ['罗盘造型', '这块像', '风水', '无所谓价', '就它', '包好', '谢', '走', '再会', '拜'] },
  { id: 'special_82', name: '找道具的古装剧组采购', type: 'special', knowledge: 0.2, budget: [5, 30], minShopLv: 2, headIcon: '🧑', phrases: ['道具用', '看着像就行', '砖头料', '便宜', '这些', '打包', '谢', '走', '拍戏用', '拜'] },
  { id: 'special_83', name: '喜欢破烂废料的先锋艺术家', type: 'special', knowledge: 0.5, budget: [10, 80], minShopLv: 2, headIcon: '🧑', phrases: ['黑癣废料', '出高价', '艺术', '这块', '完美', '收了', '包好', '谢', '走', '再会'] },
  { id: 'special_84', name: '正在搞社会实验的百万UP主', type: 'special', knowledge: 0.6, budget: [50, 500], minShopLv: 2, headIcon: '🧑', phrases: ['隐藏身份', '测试', '你没骗我', '反手打赏百万', '开玩笑', '这块买了', '包好', '谢', '走', '视频见'] },
  { id: 'special_85', name: '被附体的算命瞎子', type: 'special', knowledge: 0.4, budget: [2, 15], minShopLv: 2, headIcon: '👴', phrases: ['那块有邪气', '别买', '我看得见', '这块干净', '小心', '走了', '再会', '天机', '不可说', '拜'] },
  { id: 'special_86', name: '想砸店收保护费的黑社会混混', type: 'special', knowledge: 0.1, budget: [0, 0], minShopLv: 2, headIcon: '👨', phrases: ['保护费', '懂？', '叫保安', '你等着', '走了', '哼', '再会', '呸', '拜', '...'] },
  { id: 'special_87', name: '拿着假钞来买东西的骗子老头', type: 'special', knowledge: 0.15, budget: [20, 100], minShopLv: 2, headIcon: '👴', phrases: ['这块', '现金', '别验', '着急', '包上', '谢', '走', '快点', '再会', '拜'] },
  { id: 'special_88', name: '来化缘的少林寺方丈', type: 'special', knowledge: 0.7, budget: [0, 0], minShopLv: 3, headIcon: '👴', phrases: ['施主', '化缘', '一块石头', '开光', 'Buff', '缘分', '谢', '再会', '阿弥陀佛', '走了'] },
  { id: 'special_89', name: '假扮乞丐的微服私访首富', type: 'special', knowledge: 0.9, budget: [0, 0], minShopLv: 3, headIcon: '👴', phrases: ['行行好', '免费送块砖头', '你心善', '投资你', '开分店', '谢', '再会', '走了', '有缘', '拜'] },
  { id: 'special_90', name: '狂热的矿石收集控小学生', type: 'special', knowledge: 0.05, budget: [0.01, 0.1], minShopLv: 3, headIcon: '👦', phrases: ['卡片换', '十年攒的', '换石头', '不行吗', '求求了', '好吧', '走了', '再会', '拜', '哭'] },
  { id: 'special_91', name: '相信翡翠能治百病的老大妈', type: 'special', knowledge: 0.02, budget: [30, 150], minShopLv: 3, headIcon: '👵', phrases: ['磨粉', '冲水喝', '治百病', '最绿的', '高价', '这块', '买了', '谢', '走', '健康'] },
  { id: 'special_92', name: '戴着墨镜的神秘特工', type: 'special', knowledge: 0.8, budget: [500, 5000], minShopLv: 4, headIcon: '🕶', phrases: ['微缩胶卷', '那块', '天价', '任务', '买了', '包好', '谢', '走', '再会', '机密'] },
  { id: 'special_93', name: '来找道具的古装剧组', type: 'special', knowledge: 0.25, budget: [8, 40], minShopLv: 4, headIcon: '🧑', phrases: ['道具', '好看', '便宜', '这些', '打包', '谢', '走', '拍戏', '再会', '拜'] },
  { id: 'special_94', name: '从未来穿越回来的时空旅人', type: 'special', knowledge: 0.5, budget: [100, 1000], minShopLv: 4, headIcon: '🧑', phrases: ['未来货币', '换帝王绿', '强制', '开玩笑', '这块买了', '正常付', '谢', '走', '2077见', '拜'] },
  { id: 'special_95', name: '为了拍段子来搞怪的搞笑艺人', type: 'special', knowledge: 0.35, budget: [5, 25], minShopLv: 4, headIcon: '🤡', phrases: ['假装摔碎', '考验反应', '剪了', '这块买了', '赔', '开玩笑', '谢', '走', '段子见', '拜'] },
  { id: 'special_96', name: '拿着传国玉玺来求鉴定的神经病', type: 'special', knowledge: 0, budget: [0, 0], minShopLv: 4, headIcon: '🧑', phrases: ['换你整个店', '传国玉玺', '真的', '换不换', '不换拉倒', '走了', '再会', '哼', '拜', '...'] },
  { id: 'special_97', name: '摸金校尉', type: 'special', knowledge: 0.75, budget: [50, 300], minShopLv: 4, headIcon: '👨', phrases: ['冥器换', '土腥味', '刚出来', '这块', '考虑', '收了', '谢', '走', '再会', '拜'] },
  { id: 'special_98', name: '喝了吐真剂的间谍', type: 'special', knowledge: 0.85, budget: [200, 1000], minShopLv: 5, headIcon: '🧑', phrases: ['行业机密', '最高机密', '一边看一边说', '这块', '机密', '买了', '谢', '走', '别告诉别人', '拜'] },
  { id: 'special_99', name: '你的前女友/前男友', type: 'special', knowledge: 0.6, budget: [100, 500], minShopLv: 5, headIcon: '🧑', phrases: ['炫富', '有镇店之宝吗', '打脸', '这块', '买了', '比你强', '谢', '走', '再会', '拜'] },
  { id: 'special_100', name: '寻找丢失贡品的清朝僵尸', type: 'special', knowledge: 0.9, budget: [500, 3000], minShopLv: 5, headIcon: '🧟', phrases: ['贡品', '高冰玉佩', '征收', '半夜', '这块', '收', '谢', '走', '再会', '呜'] },
]

export const SHOP_LEVELS = [
  { level: 1, name: '起步玉坊', icon: '🏚', unlockMoney: 3000000, upgradeCost: 0, shelfCount: 3, dailyVisitors: 5, desc: '3个货架，客流稀少' },
  { level: 2, name: '临街玉器行', icon: '🏪', unlockMoney: 3000000, upgradeCost: 10000000, shelfCount: 5, dailyVisitors: 12, desc: '5个货架，客流稳定' },
  { level: 3, name: '品牌旗舰店', icon: '💎', unlockMoney: 3000000, upgradeCost: 30000000, shelfCount: 8, dailyVisitors: 25, desc: '8个货架，可雇佣导购' },
  { level: 4, name: '豪华珠宝楼', icon: '🏛', unlockMoney: 3000000, upgradeCost: 100000000, shelfCount: 12, dailyVisitors: 45, desc: '12个货架，自带安保' },
  { level: 5, name: '顶级翡翠会所', icon: '👑', unlockMoney: 3000000, upgradeCost: 500000000, shelfCount: 20, dailyVisitors: 80, desc: '20个货架，只接待顶级大鳄' },
]

// 商品等级颜色（石头 cutResult.id / 饰品 grade）
export const SHOP_GRADE_COLORS = {
  brick: { gradientFrom: '#7f1d1d', gradientTo: '#991b1b', borderColor: '#dc2626', textColor: '#fca5a5' },
  waxy: { gradientFrom: '#713f12', gradientTo: '#92400e', borderColor: '#d97706', textColor: '#fcd34d' },
  flower: { gradientFrom: '#500724', gradientTo: '#831843', borderColor: '#db2777', textColor: '#f9a8d4' },
  ice: { gradientFrom: '#0c4a6e', gradientTo: '#0369a1', borderColor: '#0ea5e9', textColor: '#7dd3fc' },
  glass: { gradientFrom: '#134e4a', gradientTo: '#0f766e', borderColor: '#14b8a6', textColor: '#5eead4' },
  imperial: { gradientFrom: '#052e16', gradientTo: '#14532d', borderColor: '#22c55e', textColor: '#86efac' },
}
